# Generated by Django 5.2.9 on 2025-12-23 06:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=10)),
                ('ai_result', models.CharField(choices=[('Unverified', 'Unverified'), ('Waste', 'Waste'), ('No Waste', 'No Waste')], db_index=True, default='Unverified', max_length=10)),
                ('waste_type', models.CharField(blank=True, help_text='Waste type detected by AI. Can be any type or combination detected by AI (e.g., "Plastic", "Mixed Plastic Waste", "Organic Food Waste", etc.). No restrictions - AI can detect unlimited types.', max_length=255, null=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score between 0.00 and 1.00', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude between -90.0 and 90.0', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude between -180.0 and 180.0', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('image_before', models.ImageField(help_text="User's photo of the waste (required)", upload_to='reports/before/%Y/%m/%d/')),
                ('image_after', models.ImageField(blank=True, help_text="Worker's proof of cleanup (optional)", null=True, upload_to='reports/after/%Y/%m/%d/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.ForeignKey(db_column='citizen_id', limit_choices_to={'role': 'Citizen'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.account')),
                ('worker', models.ForeignKey(blank=True, db_column='worker_id', limit_choices_to={'role': 'Worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='accounts.account')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['citizen', 'status'], name='reports_citizen_9734dd_idx'), models.Index(fields=['worker', 'status'], name='reports_worker__e13e7d_idx'), models.Index(fields=['status', 'ai_result'], name='reports_status_9de368_idx'), models.Index(fields=['submitted_at'], name='reports_submitt_33339f_idx')],
            },
        ),
    ]
