# Generated by Django 5.2.9 on 2025-12-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorageLog',
            fields=[
                ('image_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('profile', 'Profile')], help_text='Identifies what the image is: before, after, or profile', max_length=10)),
                ('storage_path', models.CharField(help_text='The URL/Path where the file lives in storage', max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('report', models.ForeignKey(blank=True, db_column='report_id', help_text='Links the image to a specific report (null for profile images)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_logs', to='reports.report')),
            ],
            options={
                'verbose_name': 'Image Storage Log',
                'verbose_name_plural': 'Image Storage Logs',
                'db_table': 'image_storage_log',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['report', 'image_type'], name='image_stora_report__cde1b5_idx'), models.Index(fields=['image_type', 'uploaded_at'], name='image_stora_image_t_58325c_idx'), models.Index(fields=['uploaded_at'], name='image_stora_uploade_06488c_idx')],
            },
        ),
    ]
