# Generated by Django 5.2.9 on 2025-12-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When worker accepted the report (for consistent task numbering)', null=True),
        ),
    ]
