# Generated by Django 5.2.9 on 2025-12-27 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0002_imagestoragelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('Citizen', 'Citizen'), ('Worker', 'Worker'), ('Admin', 'Admin')], db_index=True, help_text='Identifies the role of the receiver', max_length=10)),
                ('recipient_id', models.IntegerField(db_index=True, help_text='The ID from the corresponding role table (Account.account_id)')),
                ('message', models.TextField(help_text='The actual text (e.g., "Your report has been resolved!")')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Tracks if the user has opened the alert')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='For sorting and "time ago" labels')),
                ('report', models.ForeignKey(blank=True, help_text='Link to related report (if notification is about a report)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.report')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_type', 'recipient_id', 'is_read'], name='notificatio_recipie_651bd8_idx'), models.Index(fields=['recipient_id', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
