# Generated by Django 5.2.9 on 2025-12-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMonthlyStats',
            fields=[
                ('stat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('month_year', models.CharField(db_index=True, help_text='Format: YYYY-MM (e.g., "2025-12")', max_length=7)),
                ('verified_reports', models.IntegerField(default=0, help_text='Number of resolved reports this month')),
                ('badge', models.CharField(choices=[('None', 'None'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], db_index=True, default='None', help_text='Badge awarded: None, Silver (3rd), Gold (2nd), Platinum (1st)', max_length=10)),
                ('monthly_rank', models.IntegerField(blank=True, db_index=True, help_text='Position in leaderboard for this month (1st, 2nd, 3rd, etc.)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(db_column='user_id', help_text='The citizen being ranked', limit_choices_to={'role': 'Citizen'}, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='accounts.account')),
            ],
            options={
                'verbose_name': 'User Monthly Stat',
                'verbose_name_plural': 'User Monthly Stats',
                'db_table': 'user_monthly_stats',
                'ordering': ['month_year', 'monthly_rank', '-verified_reports'],
                'indexes': [models.Index(fields=['month_year', 'monthly_rank'], name='user_monthl_month_y_1a443f_idx'), models.Index(fields=['month_year', 'verified_reports'], name='user_monthl_month_y_c5b6c1_idx'), models.Index(fields=['badge', 'month_year'], name='user_monthl_badge_7dd3fc_idx'), models.Index(fields=['updated_at'], name='user_monthl_updated_b89eaa_idx')],
                'unique_together': {('user', 'month_year')},
            },
        ),
    ]
