# Generated by Django 5.2.9 on 2025-12-22 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('Citizen', 'Citizen'), ('Worker', 'Worker')], default='Citizen', max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format +92XXXXXXXXXX', regex='^\\+92\\d{10}$')])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d/')),
                ('google_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='accounts_email_04e851_idx'), models.Index(fields=['google_id'], name='accounts_google__e4828b_idx'), models.Index(fields=['role'], name='accounts_role_5bd71b_idx')],
            },
        ),
    ]
