# Generated by Django 5.2.9 on 2025-12-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, help_text='User bio/description', max_length=500, null=True),
        ),
    ]
